### ISSUE TITLE
USUARIO GRABAR - Grabar documentos

### ISSUE THREAD

**Issue by anacid** [gregorioruiz/MIR#15]
![ScreenClip.png](https://zube.io/files/gregorioruiz/8be1ba4eb3502e3246b6b6417e6a3bde.png)

1º.- En la relación de trabajadores sólo aparezcan los que están en situación de alta en la empresa.
2º.- Que las lista de los trabajadores aparezca ordenada por el código.
3º.- Si es posible poner un localizador por código.

**Comment by gregorioruiz** [comment]
No sé si puedo hacer fácilmente lo del localizador, pero con esto ya está mucho más agil
