### ISSUE TITLE
Traspaso de las facturas de venta a Contaplus

### ISSUE THREAD

**Issue by anacid** [gregorioruiz/MIR#17]
En este proceso se dan de alta o se actualizan en la contabilidad las cuentas de clientes con los datos que figuran en el programa de gestión.

**Comment by gregorioruiz** [comment]
No poner el sw de contabilizado en el proceso de exportación, sino como un proceso desde la barra inferior de la rejilla para que ellos lo ejecuten cuando efectivamente lo hayan importado a contaplus.

Poner esa columna visible en la rejilla de facturas.
